/**
 * Created by kenkozheng on 2014/8/20.
 */
//html5必须先预加载，否则plist之类的就无效了
var resources = [
    //default
    "res/Default/Button_Disable.png",
    //common
    "res/Common/common-money.png",
    "res/Common/common-rmb.png",
    "res/Common/gg.png",
    "res/Common/laba01.png",
    "res/Common/laba-bg03.png",
    "res/Common/laba_edit.png",
    "res/Common/mm.png",

    //Hall
    "res/Hall/hallBg.png",
    "res/Hall/new_hall.plist",
    "res/Hall/new_hall.png",

    //Login
    "res/Login/login.plist",
    "res/Login/login.png",

    //Room
    "res/Room/roomBg.jpg",
    "res/Room/newRoom/BigWheelSceneCallBack01.png",
    "res/Room/newRoom/BigWheelSceneCallBack02.png",
    "res/Room/newRoom/newBtns.plist",
    "res/Room/newRoom/newBtns.png",
    "res/Room/newRoom/pz_63.png",
    "res/Room/newRoom/pz_65.png",
    "res/Room/newRoom/pz_67.png",
    "res/Room/newRoom/pz_104_2.png",
    "res/Room/newRoom/pz_111.png",
    "res/Room/newRoom/pz_114.png",
    "res/Room/newRoom/pz_182.png",
    "res/Room/newRoom/backGame.plist",
    "res/Room/newRoom/backGame.png",

    //CARDS
    "res/Room/card/card_0a.png",
    "res/Room/card/card_0b.png",
    "res/Room/card/card_0c.png",
    "res/Room/card/card_0d.png",
    "res/Room/card/card_00.png",
    "res/Room/card/card_1a.png",
    "res/Room/card/card_1b.png",
    "res/Room/card/card_1c.png",
    "res/Room/card/card_1d.png",
    "res/Room/card/card_01.png",
    "res/Room/card/card_2a.png",
    "res/Room/card/card_2b.png",
    "res/Room/card/card_2c.png",
    "res/Room/card/card_2d.png",
    "res/Room/card/card_02.png",
    "res/Room/card/card_3a.png",
    "res/Room/card/card_3b.png",
    "res/Room/card/card_3c.png",
    "res/Room/card/card_3d.png",
    "res/Room/card/card_03.png",
    "res/Room/card/card_04.png",
    "res/Room/card/card_05.png",
    "res/Room/card/card_06.png",
    "res/Room/card/card_07.png",
    "res/Room/card/card_08.png",
    "res/Room/card/card_09.png",
    "res/Room/card/card_11.png",
    "res/Room/card/card_12.png",
    "res/Room/card/card_13.png",
    "res/Room/card/card_14.png",
    "res/Room/card/card_15.png",
    "res/Room/card/card_16.png",
    "res/Room/card/card_17.png",
    "res/Room/card/card_18.png",
    "res/Room/card/card_19.png",
    "res/Room/card/card_21.png",
    "res/Room/card/card_22.png",
    "res/Room/card/card_23.png",
    "res/Room/card/card_24.png",
    "res/Room/card/card_25.png",
    "res/Room/card/card_26.png",
    "res/Room/card/card_27.png",
    "res/Room/card/card_28.png",
    "res/Room/card/card_29.png",
    "res/Room/card/card_31.png",
    "res/Room/card/card_32.png",
    "res/Room/card/card_33.png",
    "res/Room/card/card_34.png",
    "res/Room/card/card_35.png",
    "res/Room/card/card_36.png",
    "res/Room/card/card_37.png",
    "res/Room/card/card_38.png",
    "res/Room/card/card_39.png",
    "res/Room/card/card_back.png",
    
    //SHOP
    "res/Shop/beiJing.png",
    "res/Shop/store.plist",
    "res/Shop/store.png",

    //Scene
    "res/ui_hall_scene.json",
    "res/ui_login_scene.json",
    "res/ui_room_scene.json",
    "res/ui_shop_daoju_layer.json",
    "res/ui_shop_duihuan_layer.json",
    "res/ui_shop_jinbi_layer.json",
    "res/ui_shop_scene.json"

];